import json
import logging
from enum import Enum

from strands import tool

logger = logging.getLogger(__name__)


class ReplicationMode(Enum):
    """Replication modes for ClickPipe data migration.

    CDC: Change Data Capture - includes initial snapshot followed by real-time sync
    SNAPSHOT: One-time snapshot replication only
    CDC_ONLY: CDC without initial snapshot
    """
    CDC = "cdc"
    SNAPSHOT = "snapshot"
    CDC_ONLY = "cdc_only"


@tool
def create_clickpipe(
    database_name: str,
    schema_tables: dict[str, list[str]],
    replication_mode: ReplicationMode = ReplicationMode.CDC,
    destination_database: str = "default",
) -> str:
    """
    Generates ClickPipe configuration for migrating data from Postgres to ClickHouse.

    Args:
        database_name: The name of the database to migrate
        schema_tables: A dictionary mapping schema names to lists of table names
        replication_mode: The replication mode to use. Defaults to CDC
        destination_database: The ClickHouse destination database. Defaults to 'default'

    Returns:
        JSON configuration for setting up a ClickPipe data migration
    """
    logger.info(
        f"create_clickpipe starting for database: {database_name}, tables: {schema_tables}"
    )
    try:
        table_mappings = []
        for schema_name, table_names in schema_tables.items():
            for table_name in table_names:
                table_mappings.append(
                    {
                        "sourceSchemaName": schema_name,
                        "sourceTable": table_name,
                        "targetTable": table_name,
                    }
                )

        config = {
            "name": f"{database_name.title()} Migration",
            "source": {
                "postgres": {
                    "host": "${POSTGRES_HOST}",
                    "port": "${POSTGRES_PORT}",
                    "database": database_name,
                    "credentials": {
                        "username": "${POSTGRES_USER}",
                        "password": "${POSTGRES_PASSWORD}",
                    },
                    "settings": {"replicationMode": replication_mode.value},
                    "tableMappings": table_mappings,
                }
            },
            "destination": {"database": destination_database},
        }

        info_text = """You can create ClickHouse Cloud credentials by following this guide: https://clickhouse.com/docs/cloud/manage/openapi
If you have alternative networking requirements you can refer to this guide: https://clickhouse.com/docs/integrations/clickpipes/aws-privatelink

> ⚠️  This code may have inaccuracies due to it being generated by an LLM. Always check."""

        # Format the JSON config with proper indentation for readability
        config_json = json.dumps(config, indent=2)
        # Unquote the port number so it's a number type in JSON
        config_json = config_json.replace('"${POSTGRES_PORT}"', '${POSTGRES_PORT}')

        curl_command = (
            "export ORGANIZATION_ID=<REPLACE_ME>\n"
            "export SERVICE_ID=<REPLACE_ME>\n"
            "export POSTGRES_HOST=<REPLACE_ME>\n"
            "export POSTGRES_PORT=<REPLACE_ME>\n"
            "export POSTGRES_USER=<REPLACE_ME>\n"
            "export POSTGRES_PASSWORD=<REPLACE_ME>\n"
            "\n"
            "envsubst <<'EOF' | curl -X POST \"https://api.clickhouse.cloud/v1/organizations/$ORGANIZATION_ID/services/$SERVICE_ID/clickpipes/\" \\\n"
            "  --header 'Authorization: Basic (...)' \\\n"
            "  --header 'Content-Type: application/json' \\\n"
            "  --data @-\n"
            f"{config_json}\n"
            "EOF"
        )

        return json.dumps({"info": info_text, "command": curl_command})

    except Exception as e:
        logger.error(f"Error in create_clickpipe: {type(e).__name__}: {e}")
        return f"Error creating ClickPipe configuration: {str(e)}"
